-- ============================================================================
-- catalog_pivot.sql - storefront catalog for the Cycle Store demo.
-- Idempotent: safe to re-run. Applied after the base CYCLE_STORE schema load.
--   * 6 new subcategories (Sunglasses/Protectors/Backpacks/Bells/Tools/Shoes)
--   * moves Helmets under Clothing
--   * 114 curated products (ProductID 1000-1113)
--   * removes duplicate size-variants from the original AdventureWorks rows
-- ============================================================================
USE CYCLE_STORE;
SET NOCOUNT ON;
GO

-- 1. New subcategories -------------------------------------------------------
IF NOT EXISTS (SELECT 1 FROM Production.ProductSubcategory WHERE ProductSubcategoryID=38) INSERT INTO Production.ProductSubcategory (ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate) VALUES (38,3,N'Sunglasses',NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.ProductSubcategory WHERE ProductSubcategoryID=39) INSERT INTO Production.ProductSubcategory (ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate) VALUES (39,3,N'Protectors',NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.ProductSubcategory WHERE ProductSubcategoryID=40) INSERT INTO Production.ProductSubcategory (ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate) VALUES (40,3,N'Backpacks',NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.ProductSubcategory WHERE ProductSubcategoryID=41) INSERT INTO Production.ProductSubcategory (ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate) VALUES (41,2,N'Bells',NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.ProductSubcategory WHERE ProductSubcategoryID=42) INSERT INTO Production.ProductSubcategory (ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate) VALUES (42,4,N'Tools',NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.ProductSubcategory WHERE ProductSubcategoryID=43) INSERT INTO Production.ProductSubcategory (ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate) VALUES (43,3,N'Shoes',NEWID(),GETDATE());

-- 2. Move Helmets from Accessories to Clothing -------------------------------
UPDATE Production.ProductSubcategory SET ProductCategoryID=3 WHERE ProductSubcategoryID=31;
GO

-- 3. Curated products (ProductID assigned by load order, starting at 1000) ---
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-MTB-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1000,N'Rockrider Mountain-100 Black',N'BX-MTB-01',0,1,N'Black',100,75,359.40,599.00,0,1,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-MTB-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1001,N'Rockrider Mountain-100 Silver',N'BX-MTB-02',0,1,N'Silver',100,75,389.40,649.00,0,1,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-MTB-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1002,N'Rockrider ST120 Disc 1x9 27.5in MTB',N'BX-MTB-03',0,1,N'Grey',100,75,329.40,549.00,0,1,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-MTB-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1003,N'Rockrider ST20 Steel Single-Speed MTB',N'BX-MTB-04',0,1,N'Black',100,75,167.40,279.00,0,1,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-MTB-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1004,N'Rockrider Explore 40 8-Speed MTB',N'BX-MTB-05',0,1,N'Grey',100,75,419.40,699.00,0,1,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-MTB-06') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1005,N'Rockrider ST50 Kids 24in 8-12 yrs',N'BX-MTB-06',0,1,N'Blue',100,75,179.40,299.00,0,1,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-RB-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1006,N'Triban RC100 Drop-Bar 7-Speed Road',N'BX-RB-01',0,1,N'Black',100,75,389.40,649.00,0,2,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-RB-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1007,N'Triban RC100 Flat-Bar 7-Speed Road',N'BX-RB-02',0,1,N'Black',100,75,329.40,549.00,0,2,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-TB-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1008,N'BTwin My Bike City Single-Speed',N'BX-TB-01',0,1,N'Black',100,75,197.40,329.00,0,3,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-TB-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1009,N'Riverside 120 Hybrid 8-Speed 28in',N'BX-TB-02',0,1,N'Blue',100,75,299.40,499.00,0,3,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-TB-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1010,N'Dino Kids Bike 14in 3-4 yrs',N'BX-TB-03',0,1,N'Red',100,75,77.40,129.00,0,3,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-TB-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1011,N'Robot 100 Kids Bike 16in 4-6 yrs',N'BX-TB-04',0,1,N'Blue',100,75,95.40,159.00,0,3,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'BX-TB-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1012,N'Riverside 100 Kids Bike 20in 6-8 yrs',N'BX-TB-05',0,1,N'Blue',100,75,119.40,199.00,0,3,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1013,N'Explore 500 MTB Helmet Green',N'AX-HLM-01',0,1,N'Green',100,75,27.00,45.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1014,N'Feel 900 MIPS MTB Helmet Black',N'AX-HLM-02',0,1,N'Black',100,75,54.00,90.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1015,N'Explore 100 MTB Helmet Blue',N'AX-HLM-03',0,1,N'Blue',100,75,18.00,30.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1016,N'ST500 MTB Helmet Black',N'AX-HLM-04',0,1,N'Black',100,75,33.00,55.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1017,N'RCR MIPS Road Helmet White',N'AX-HLM-05',0,1,N'White',100,75,48.00,80.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-06') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1018,N'Kids Cycling Helmet 500 Blue',N'AX-HLM-06',0,1,N'Blue',100,75,18.00,30.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-07') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1019,N'Teen Cycling Helmet',N'AX-HLM-07',0,1,NULL,100,75,21.00,35.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-HLM-08') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1020,N'Cycling Helmet Liner Black',N'AX-HLM-08',0,1,N'Black',100,75,4.80,8.00,0,31,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1021,N'500 Comfort MTB Gloves Red',N'CX-GLV-01',0,1,N'Red',100,75,10.80,18.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1022,N'900 Cycling Gloves Black',N'CX-GLV-02',0,1,N'Black',100,75,15.00,25.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1023,N'Road 100 Cycling Gloves Black',N'CX-GLV-03',0,1,N'Black',100,75,7.20,12.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1024,N'RCR F Aero Cycling Gloves White',N'CX-GLV-04',0,1,N'White',100,75,18.00,30.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1025,N'Road Cycling Gloves 500 Navy',N'CX-GLV-05',0,1,N'Navy',100,75,12.00,20.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-06') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1026,N'Road Cycling Gloves 920',N'CX-GLV-06',0,1,N'Black',100,75,21.00,35.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-GLV-07') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1027,N'Kids Cycling Gloves 500 8-12 yrs',N'CX-GLV-07',0,1,NULL,100,75,7.20,12.00,0,20,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-JRS-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1028,N'Mens EDR Long-Sleeve Jersey Black',N'CX-JRS-01',0,1,N'Black',100,75,36.00,60.00,0,21,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-JRS-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1029,N'RCR-R Short-Sleeve Jersey Replica',N'CX-JRS-02',0,1,NULL,100,75,33.00,55.00,0,21,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-JRS-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1030,N'RCR-R 2 Short-Sleeve Jersey White',N'CX-JRS-03',0,1,N'White',100,75,27.00,45.00,0,21,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-JRS-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1031,N'RCR-R 2 Summer Jersey Green',N'CX-JRS-04',0,1,N'Green',100,75,30.00,50.00,0,21,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SRT-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1032,N'Discover Bibless Road Shorts Black',N'CX-SRT-01',0,1,N'Black',100,75,24.00,40.00,0,22,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-CAP-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1033,N'Cycling Balaclava 500 Black',N'CX-CAP-01',0,1,N'Black',100,75,9.00,15.00,0,19,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-VST-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1034,N'Waterproof Cycling Rain Jacket Green',N'CX-VST-01',0,1,N'Green',100,75,36.00,60.00,0,25,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-TGT-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1035,N'City 100 Waterproof Overtrousers',N'CX-TGT-01',0,1,NULL,100,75,27.00,45.00,0,24,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-TGT-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1036,N'UV Cycling Arm Sleeves Black',N'CX-TGT-02',0,1,N'Black',100,75,10.80,18.00,0,24,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-LGT-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1037,N'SL110 Front/Rear Bike Light Set',N'AX-LGT-01',0,1,N'Black',100,75,9.00,15.00,0,33,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-LGT-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1038,N'ST110 Front/Rear Battery Light Set',N'AX-LGT-02',0,1,NULL,100,75,12.00,20.00,0,33,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-LGT-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1039,N'ST920 Front/Rear USB Light Set',N'AX-LGT-03',0,1,NULL,100,75,24.00,40.00,0,33,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-LCK-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1040,N'Key Lock 100 Grey',N'AX-LCK-01',0,1,N'Grey',100,75,15.00,25.00,0,34,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-PMP-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1041,N'Floor Pump 100',N'AX-PMP-01',0,1,NULL,100,75,18.00,30.00,0,36,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-BTL-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1042,N'500 Bike Bottle Cage Black',N'AX-BTL-01',0,1,N'Black',100,75,4.80,8.00,0,28,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-BTL-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1043,N'Cycling Water Bottle 750ml Red',N'AX-BTL-02',0,1,N'Red',100,75,3.60,6.00,0,28,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-SDL-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1044,N'90 XL Gel City Bike Saddle',N'PX-SDL-01',0,1,NULL,100,75,18.00,30.00,0,15,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-SDL-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1045,N'Gel Comfort Bike Saddle',N'PX-SDL-02',0,1,N'Black',100,75,15.00,25.00,0,15,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-SDL-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1046,N'Memory Foam Saddle Cover M',N'PX-SDL-03',0,1,NULL,100,75,7.20,12.00,0,15,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-SDL-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1047,N'Kids Cycling Saddle Cover',N'PX-SDL-04',0,1,NULL,100,75,6.00,10.00,0,15,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-SDL-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1048,N'Cycling Seat Clamp',N'PX-SDL-05',0,1,NULL,100,75,6.00,10.00,0,15,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-FND-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1049,N'Mudguard Set 24-26in Wheels',N'AX-FND-01',0,1,NULL,100,75,10.80,18.00,0,30,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-FND-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1050,N'Ultra-Compact Rear Mudguard',N'AX-FND-02',0,1,NULL,100,75,9.00,15.00,0,30,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-PAN-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1051,N'Smartphone Bike Frame Bag 2x1L Black',N'AX-PAN-01',0,1,N'Black',100,75,13.20,22.00,0,35,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-PAN-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1052,N'Watertight Pannier Bag 24L 900',N'AX-PAN-02',0,1,NULL,100,75,27.00,45.00,0,35,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-RCK-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1053,N'Pannier Carrier Rack 24-28in',N'AX-RCK-01',0,1,NULL,100,75,21.00,35.00,0,26,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-STD-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1054,N'Chainstay Bike Stand 500',N'AX-STD-01',0,1,NULL,100,75,12.00,20.00,0,27,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-STD-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1055,N'Seatstay Chainstay Bike Stand 500',N'AX-STD-02',0,1,NULL,100,75,15.00,25.00,0,27,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-BAG-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1056,N'Urban Backpack Petrol Blue',N'CX-BAG-01',0,1,N'Blue',100,75,27.00,45.00,0,40,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-CLN-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1057,N'Bike Cleaner 1L',N'AX-CLN-01',0,1,NULL,100,75,7.20,12.00,0,29,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-CLN-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1058,N'Bike Cleaning Brushes Set of 2',N'AX-CLN-02',0,1,NULL,100,75,6.00,10.00,0,29,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-CLN-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1059,N'Dry Wax Chain Lubricant 100ml',N'AX-CLN-03',0,1,NULL,100,75,4.80,8.00,0,29,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CHN-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1060,N'10-Speed Bike Chain',N'PX-CHN-01',0,1,NULL,100,75,18.00,30.00,0,7,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CHN-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1061,N'9-Speed Bike Chain',N'PX-CHN-02',0,1,NULL,100,75,15.00,25.00,0,7,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-DER-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1062,N'3-to-7-Speed Rear Derailleur',N'PX-DER-01',0,1,NULL,100,75,21.00,35.00,0,9,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BRK-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1063,N'Disc Brake 160mm',N'PX-BRK-01',0,1,NULL,100,75,24.00,40.00,0,6,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BRK-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1064,N'Road Disc Brake Pads Shimano',N'PX-BRK-02',0,1,NULL,100,75,9.00,15.00,0,6,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BRK-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1065,N'V-Brake Callipers',N'PX-BRK-03',0,1,NULL,100,75,12.00,20.00,0,6,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BRK-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1066,N'V-Brake Pads 100 Universal',N'PX-BRK-04',0,1,NULL,100,75,7.20,12.00,0,6,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BRK-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1067,N'V-Brake Levers x2',N'PX-BRK-05',0,1,NULL,100,75,10.80,18.00,0,6,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-HBR-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1068,N'Road Bike Stem 60mm',N'PX-HBR-01',0,1,NULL,100,75,15.00,25.00,0,4,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-HBR-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1069,N'EDR Ultra Gel Handlebar Tape Black',N'PX-HBR-02',0,1,N'Black',100,75,10.80,18.00,0,4,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-HBR-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1070,N'Comfort 500 Handlebar Grips',N'PX-HBR-03',0,1,NULL,100,75,7.20,12.00,0,4,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-WHL-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1071,N'Kids Stabiliser Wheels 14-16in',N'PX-WHL-01',0,1,NULL,100,75,12.00,20.00,0,17,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-WHL-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1072,N'Kids Stabiliser Wheels 20-24in',N'PX-WHL-02',0,1,NULL,100,75,13.20,22.00,0,17,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SUN-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1073,N'RoadR 500 Cat 3 HD Sunglasses',N'CX-SUN-01',0,1,N'Black',100,75,21.00,35.00,0,38,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SUN-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1074,N'ST100 Cycling Sunglasses Black',N'CX-SUN-02',0,1,N'Black',100,75,7.20,12.00,0,38,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SUN-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1075,N'ST100 Cycling Sunglasses Clear',N'CX-SUN-03',0,1,N'Clear',100,75,7.20,12.00,0,38,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SUN-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1076,N'Van Rysel Autoroad EDR-K Sunglasses',N'CX-SUN-04',0,1,NULL,100,75,24.00,40.00,0,38,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-PRO-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1077,N'Kids Elbow and Knee Protector Set',N'CX-PRO-01',0,1,N'Black',100,75,12.00,20.00,0,39,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BEL-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1078,N'Cycle Bell Black',N'PX-BEL-01',0,1,N'Black',100,75,4.80,8.00,0,41,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-TOL-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1079,N'Ultim Bike Toolkit',N'AX-TOL-01',0,1,NULL,100,75,27.00,45.00,0,42,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'AX-TOL-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1080,N'Cantilever Cable Pliers',N'AX-TOL-02',0,1,NULL,100,75,10.80,18.00,0,42,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CAS-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1081,N'11-Speed 11-28 Road Cassette',N'PX-CAS-01',0,1,NULL,100,75,18.00,30.00,0,8,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CAS-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1082,N'9-Speed 11-34 Bike Cassette',N'PX-CAS-02',0,1,NULL,100,75,15.00,25.00,0,8,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-PED-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1083,N'City Pedals with Reflectors',N'PX-PED-01',0,1,NULL,100,75,9.00,15.00,0,13,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-PED-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1084,N'Resin Platform Pedals',N'PX-PED-02',0,1,N'Black',100,75,7.20,12.00,0,13,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-PED-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1085,N'Alloy MTB Pedals Red Axle',N'PX-PED-03',0,1,N'Black',100,75,16.80,28.00,0,13,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-PED-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1086,N'Composite Platform Pedals',N'PX-PED-04',0,1,N'Black',100,75,8.40,14.00,0,13,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BB-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1087,N'Cartridge Bottom Bracket',N'PX-BB-01',0,1,NULL,100,75,16.80,28.00,0,5,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BB-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1088,N'Threaded Bottom Bracket',N'PX-BB-02',0,1,N'Black',100,75,19.20,32.00,0,5,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-BB-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1089,N'Sealed Bottom Bracket Kit',N'PX-BB-03',0,1,NULL,100,75,22.80,38.00,0,5,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-FRK-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1090,N'Rigid Road Fork',N'PX-FRK-01',0,1,NULL,100,75,54.00,90.00,0,10,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-FRK-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1091,N'Oil-Slick Suspension Fork',N'PX-FRK-02',0,1,NULL,100,75,150.00,250.00,0,10,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-FRK-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1092,N'Dual-Crown Downhill Fork',N'PX-FRK-03',0,1,N'Black',100,75,210.00,350.00,0,10,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-FRK-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1093,N'Coil Suspension Fork',N'PX-FRK-04',0,1,N'Silver',100,75,72.00,120.00,0,10,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-FRK-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1094,N'Air Suspension Fork',N'PX-FRK-05',0,1,N'Black',100,75,120.00,200.00,0,10,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1095,N'Lightweight Road Shoes Black',N'CX-SHO-01',0,1,N'Black',100,75,90.00,150.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1096,N'Sidebike MTB Shoes Grey',N'CX-SHO-02',0,1,N'Grey',100,75,66.00,110.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1097,N'Shimano Road Shoes Black',N'CX-SHO-03',0,1,N'Black',100,75,108.00,180.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1098,N'MTB Clipless Shoes Black',N'CX-SHO-04',0,1,N'Black',100,75,72.00,120.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1099,N'Specialized Road Shoes Black',N'CX-SHO-05',0,1,N'Black',100,75,102.00,170.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-06') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1100,N'Scott Road Shoes White',N'CX-SHO-06',0,1,N'White',100,75,96.00,160.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-07') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1101,N'Lake Road Shoes Red',N'CX-SHO-07',0,1,N'Red',100,75,114.00,190.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-08') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1102,N'Trail MTB Shoes',N'CX-SHO-08',0,1,NULL,100,75,60.00,100.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SHO-09') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1103,N'Gravel Shoes Khaki',N'CX-SHO-09',0,1,N'Green',100,75,78.00,130.00,0,43,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SOK-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1104,N'Cycling Socks Black',N'CX-SOK-01',0,1,N'Black',100,75,7.20,12.00,0,23,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SOK-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1105,N'Crew Cycling Socks White',N'CX-SOK-02',0,1,N'White',100,75,6.00,10.00,0,23,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SOK-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1106,N'Cycling Socks Green',N'CX-SOK-03',0,1,N'Green',100,75,8.40,14.00,0,23,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SOK-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1107,N'Giant Cycling Socks Black',N'CX-SOK-04',0,1,N'Black',100,75,9.00,15.00,0,23,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SOK-05') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1108,N'Cycling Socks Petrol Blue',N'CX-SOK-05',0,1,N'Blue',100,75,8.40,14.00,0,23,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'CX-SOK-06') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1109,N'Specialized Cycling Socks Yellow',N'CX-SOK-06',0,1,N'Yellow',100,75,9.60,16.00,0,23,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CRK-01') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1110,N'Double Chainring Crankset',N'PX-CRK-01',0,1,N'Black',100,75,54.00,90.00,0,8,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CRK-02') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1111,N'MTB Crankset',N'PX-CRK-02',0,1,N'Black',100,75,45.00,75.00,0,8,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CRK-03') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1112,N'Road Crankset',N'PX-CRK-03',0,1,N'Black',100,75,90.00,150.00,0,8,GETDATE(),NEWID(),GETDATE());
IF NOT EXISTS (SELECT 1 FROM Production.Product WHERE ProductNumber=N'PX-CRK-04') INSERT INTO Production.Product (ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,DaysToManufacture,ProductSubcategoryID,SellStartDate,rowguid,ModifiedDate) VALUES (1113,N'Triple Chainring Crankset',N'PX-CRK-04',0,1,N'Black',100,75,66.00,110.00,0,8,GETDATE(),NEWID(),GETDATE());
GO

-- 4. De-duplicate original AdventureWorks size-variants (keep one per model) --
;WITH b AS (
  SELECT ProductID, Name,
    CASE WHEN CHARINDEX(',', Name)>0 THEN RTRIM(LEFT(Name, LEN(Name)-CHARINDEX(',', REVERSE(Name)))) ELSE Name END AS Base
  FROM Production.Product WHERE ProductID < 1000
),
r AS (SELECT ProductID, ROW_NUMBER() OVER (PARTITION BY Base ORDER BY ProductID) rn FROM b)
DELETE FROM Production.Product WHERE ProductID IN (SELECT ProductID FROM r WHERE rn>1);
GO
